### PR TITLE
[#3012] Add NODEFINCREASE modifier to DENSITYINCREASE power

### LINKED ISSUE #3012: Add modifier support: DENSITYINCREASE > NODEFINCREASE
Modifier NODEFINCREASE is not accounted for in DENSITYINCREASE.

Reproduction steps:
1. Upload an HDC file with the example below.
2. Enable density increase power
3. Note increase in ED and PD

Expected behavior:
1. Upload an HDC file with the example below
2. Enable density increase power
3. Note no change in ED/PD

Example XML:
```xml
    <POWER XMLID="DENSITYINCREASE" ID="1761013989138" BASECOST="0.0" LEVELS="8" ALIAS="Gravitic Lock" POSITION="5" MULTIPLIER="1.0" GRAPHIC="Burst" COLOR="255 255 255" SFX="Default" SHOW_ACTIVE_COST="Yes" INCLUDE_NOTES_IN_PRINTOUT="Yes" PARENTID="1739145282228" NAME="" QUANTITY="1" AFFECTS_PRIMARY="No" AFFECTS_TOTAL="Yes">
      <NOTES />
      <MODIFIER XMLID="NODEFINCREASE" ID="1761605100391" BASECOST="-0.5" LEVELS="0" ALIAS="No Defense Increase" POSITION="-1" MULTIPLIER="1.0" GRAPHIC="Burst" COLOR="255 255 255" SFX="Default" SHOW_ACTIVE_COST="Yes" OPTION="PDED" OPTIONID="PDED" OPTION_ALIAS="does not provide PD or ED" INCLUDE_NOTES_IN_PRINTOUT="Yes" NAME="" COMMENTS="" PRIVATE="No" FORCEALLOW="No">
        <NOTES />
      </MODIFIER>
    </POWER>
```

### PR DESCRIPTION
**Pull request by ndguarino**
Add NODEFINCREASE to DENSITYINCREASE power. Closes #3012

* Adds NODEFINCREASE support, including all options (ED, PD, EDPD)
* Refactors tests for DENSITYINCREASE to better test increases or lack thereof, as well as all options.
    * Use of undefined is due to lack of actor initialization of characteristic.*.value in tests.
* Improves readability of description factory for DENSITYINCREASE.

### CODE REVIEW

File: module/config.mjs [hunk 1]
```diff
@@ -5765,9 +5765,21 @@ function addPower(powerDescription6e, powerOverrideFor5e) {
...
-                return `${item.system.ALIAS} (${Math.pow(2, item.system.LEVELS) * 100} kg mass, +${
-                    noStrIncrease ? 0 : item.system.LEVELS * 5
-                } STR, +${item.system.LEVELS} PD/ED, -${hexDistanceToSystemDisplayString(item.system.LEVELS, item.actor)} KB)`;
+                const noDefIncrease = item.modifiers.find((mod) => mod.XMLID === "NODEFINCREASE");
+
+                const strDisplay = `+${noStrIncrease ? 0 : item.system.LEVELS * 5} STR`;
+                const massDisplay = `${Math.pow(2, item.system.LEVELS) * 100} kg mass`;
+                const kbDisplay = `-${hexDistanceToSystemDisplayString(item.system.LEVELS, item.actor)} KB`;
+                // NODEFINCREASE allows for ED, PD, or EDPD as option.
+                const armorDisplay = {
```
[the remark this answers is not in the document]
Comment (ndguarino) [reply module/config.mjs]: Also, it's slightly unclear here if we're trying to match the designer here. If we are, this will require slight further refactoring, however there's also places where the designer's formatting is deviated from and this seems more clear.

If we want to match the designer:
* Fully omit this from the display if NODEFINCREASE PDED
* Only show +PD or +ED if it has a value.
* Due to the omit above, we'll likely need to dynamically build this. Something like `[massDisplay, strDisplay, ...].filter(Boolean).join(', ')` would work.

[the remark this answers is not in the document]
Comment (ndguarino) [reply module/config.mjs]: @aeauseth Resolved in [0ae49da](https://github.com/dmdorman/hero6e-foundryvtt/pull/3013/commits/0ae49dac9a342793112dc662767ddc5ef0bfd546)

File: module/config.mjs [hunk 2]
```diff
@@ -5765,9 +5765,25 @@ function addPower(powerDescription6e, powerOverrideFor5e) {
...
-                    noStrIncrease ? 0 : item.system.LEVELS * 5
-                } STR, +${item.system.LEVELS} PD/ED, -${hexDistanceToSystemDisplayString(item.system.LEVELS, item.actor)} KB)`;
+                const noDefIncrease = item.modifiers.find((mod) => mod.XMLID === "NODEFINCREASE");
+
+                const strDisplay = `+${noStrIncrease ? 0 : item.system.LEVELS * 5} STR`;
+                const massDisplay = `${Math.pow(2, item.system.LEVELS) * 100} kg mass`;
+                const kbDisplay = `-${hexDistanceToSystemDisplayString(item.system.LEVELS, item.actor)} KB`;
+                // NODEFINCREASE allows for ED, PD, or EDPD as option.
+                const armorDisplay = (() => {
+                    const noPdIncrease = noDefIncrease?.OPTION.includes("PD");
```
Comment (phBalance) [inline module/config.mjs]: Please use `OPTIONID` where it exists (and it seems to exist here) as it can't be modified by users in HDC (`OPTION` can)

File: module/config.mjs [hunk 3]
```diff
@@ -5765,9 +5765,25 @@ function addPower(powerDescription6e, powerOverrideFor5e) {
             baseEffectDicePartsBundle: noDamageBaseEffectDicePartsBundle,
             descriptionFactory: function (item) {
                 const noStrIncrease = item.modifiers.find((mod) => mod.XMLID === "NOSTRINCREASE");
-                return `${item.system.ALIAS} (${Math.pow(2, item.system.LEVELS) * 100} kg mass, +${
-                    noStrIncrease ? 0 : item.system.LEVELS * 5
-                } STR, +${item.system.LEVELS} PD/ED, -${hexDistanceToSystemDisplayString(item.system.LEVELS, item.actor)} KB)`;
+                const noDefIncrease = item.modifiers.find((mod) => mod.XMLID === "NODEFINCREASE");
```
Comment (phBalance) [inline module/config.mjs]: nitpick: Given the way you've moved the defense string building into an IIFE, should it be in the IIFE as well?

File: module/config.mjs [hunk 4]
```diff
@@ -5765,9 +5765,25 @@ function addPower(powerDescription6e, powerOverrideFor5e) {
...
+                    const displayTypes = [noPdIncrease ? "" : "PD", noEdIncrease ? "" : "ED"].filter(Boolean).join("/");
+                    return `+${item.system.LEVELS} ${displayTypes}`;
+                })();
+
+                const details = [massDisplay, strDisplay, armorDisplay, kbDisplay].filter(Boolean).join(", ");
+
+                return `${item.system.ALIAS} (${details})`;
             },
             xml: `<POWER XMLID="DENSITYINCREASE" ID="1709333874268" BASECOST="0.0" LEVELS="1" ALIAS="Density Increase" POSITION="31" MULTIPLIER="1.0" GRAPHIC="Burst" COLOR="255 255 255" SFX="Default" SHOW_ACTIVE_COST="Yes" INCLUDE_NOTES_IN_PRINTOUT="Yes" NAME="" QUANTITY="1" AFFECTS_PRIMARY="No" AFFECTS_TOTAL="Yes"></POWER>`,
         },
```
Comment (phBalance) [inline module/config.mjs]: note for the future: missing the MODIFIER definitions for these (NOSTRINCREASE && NODEFINCREASE) as we want them for the future and consistency when we need to address cost differences. I will add them in a separate PR (along with a bunch of other missing ones).

File: module/item/item.mjs [hunk 5]
```diff
@@ -407,9 +407,14 @@ export class HeroSystem6eItem extends Item {
 
             if (this.id && this.system.XMLID === "DENSITYINCREASE") {
                 const noStrIncrease = this.modifiers.find((mod) => mod.XMLID === "NOSTRINCREASE");
+                const noDefIncrease = this.modifiers.find((mod) => mod.XMLID === "NODEFINCREASE");
+                // NODEFINCREASE allows for ED, PD, or EDPD as option.
+                const noDefIncreasePd = noDefIncrease?.OPTION.includes("PD");
```
Comment (phBalance) [inline module/item/item.mjs]: issue: As with above, use `OPTIONID` please.

File: module/item/item.mjs [hunk 6]
```diff
@@ -407,9 +407,14 @@ export class HeroSystem6eItem extends Item {
...
+                const noDefIncreaseEd = noDefIncrease?.OPTION.includes("ED");
+
                 const strAdd = noStrIncrease ? 0 : Math.floor(this.system.LEVELS) * 5;
```
Comment (phBalance) [inline module/item/item.mjs]: note: new data model coerces LEVELS into an int. I know that you just copied, but you could rip the `Math.floor` out from here.

File: module/testing/testing-upload.mjs [hunk 7]
```diff
@@ -8369,52 +8369,192 @@ export function registerUploadTests(quench) {
...
+                        before(async function () {
+                            actor = await createQuenchActor({ quench: this, is5e: true });
+                            item = await HeroSystem6eItem.create(HeroSystem6eItem.itemDataFromXml(contents, actor), {
+                                parent: actor,
+                            });
 
-                        item = new HeroSystem6eItem(HeroSystem6eItem.itemDataFromXml(contents, actor), {
-                            parent: actor,
+                            await actor.FullHealth();
+                            await item.toggle();
```
Comment (phBalance) [inline module/testing/testing-upload.mjs]: issue: you're relying on the unspoken behaviour that the density increase item is turned off by default. Unfortunately parts of this test will pass if it's on or off (i.e. STR is the same with DI on and off). You could get rid of the STR test or you will have to assert that DI (actually DI active effect) is active as a test.

File: module/testing/testing-upload.mjs [hunk 8]
```diff
@@ -8369,52 +8369,192 @@ export function registerUploadTests(quench) {
...
+                            });
+
+                            await actor.FullHealth();
+                            await item.toggle();
+                        });
+
+                        it("description", function () {
+                            assert.equal(
+                                item.system.description,
+                                `Density Increase (3200 kg mass, +25 STR, +5 ED, -5" KB) (25 Active Points); No Defense Increase (does not provide PD; -1/4)`,
```
Comment (phBalance) [inline module/testing/testing-upload.mjs]: thought: I realize HD doesn't indicate that it's +0 PD for this case, but I wonder if it would be easier to code and more explicit if we had that. I can live with HD although I frequently don't like it.

File: module/testing/testing-upload.mjs [hunk 9]
```diff
@@ -8369,52 +8369,192 @@ export function registerUploadTests(quench) {
...
+                        let item, actor;
+
+                        before(async function () {
+                            actor = await createQuenchActor({ quench: this, is5e: true });
+                            item = await HeroSystem6eItem.create(HeroSystem6eItem.itemDataFromXml(contents, actor), {
+                                parent: actor,
+                            });
+
+                            await actor.FullHealth();
+                            await item.toggle();
```
Comment (phBalance) [inline module/testing/testing-upload.mjs]: issue: see note about `toggle()` in test suite above.

File: module/testing/testing-upload.mjs [hunk 10]
```diff
@@ -8369,52 +8369,192 @@ export function registerUploadTests(quench) {
...
+                            assert.equal(item.activePoints, 25);
+                        });
+
+                        it("does not increase PD", function () {
+                            assert.equal(actor.system.characteristics.pd.core, actor.system.characteristics.pd.value);
+                        });
+
+                        it("does increase ED", function () {
+                            assert.notEqual(
+                                actor.system.characteristics.ed.core,
```
Comment (phBalance) [inline module/testing/testing-upload.mjs]: thought: I would have tested that the value is core + 5 but this is probably fine too.

**Review by phBalance — CHANGES_REQUESTED** [review]
Some picky comments and observations. Looks like it should work. Thank you for doing a test for it!

File: module/config.mjs (hunk 3 above)
Comment (ndguarino) [reply module/config.mjs]: Resolved in [077210b](https://github.com/dmdorman/hero6e-foundryvtt/pull/3013/commits/077210bd41bc51ebc5a107ed0b61a38009da8ff1)

File: module/item/item.mjs (hunk 5 above)
Comment (ndguarino) [reply module/item/item.mjs]: Resolved in [077210b](https://github.com/dmdorman/hero6e-foundryvtt/pull/3013/commits/077210bd41bc51ebc5a107ed0b61a38009da8ff1)

File: module/config.mjs (hunk 4 above)
Comment (ndguarino) [reply module/config.mjs]: Resolved (I think) in b9b73a3. Might need a cost function, it's not fully clear how basecost interacts. Will explore that later.

File: module/testing/testing-upload.mjs [hunk 11]
```diff
@@ -8369,52 +8369,192 @@ export function registerUploadTests(quench) {
...
+                            assert.equal(item.realCost, 17);
+                        });
+
+                        it("activePoints", function () {
+                            assert.equal(item.activePoints, 25);
+                        });
+
+                        it("does not increase STR", function () {
+                            assert.equal(actor.system.characteristics.str.core, actor.system.characteristics.str.value);
+                        });
```
[the remark this answers is not in the document]
Comment (ndguarino) [reply module/testing/testing-upload.mjs]: Done.

**Comment by ndguarino** [comment]
Added a fix for #3024 in here as I noticed it while testing as well.

**Review by phBalance — APPROVED** [review]
LGTM
